version: '3'

services:
  jobs:
    build:
      context: .
      dockerfile: Dockerfile
    image: stevejobs
    container_name: jobs
    restart: unless-stopped
    command: tail -f /dev/null
    env_file:
      - ./.env
    networks:
      - stevejobs-network
  ofelia:
    image: mcuadros/ofelia:latest
    container_name: ofelia
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./ofelia/config.ini:/etc/ofelia/config.ini
      - ./logs:/tmp/logs
    depends_on:
      - jobs
    restart: always
networks:
  stevejobs-network:
    driver: bridge
