-- This template script will read transactions file generated by the go package and load to mysql database

DROP TABLE IF EXISTS temp_Transactions;
CREATE TABLE IF NOT EXISTS `temp_Transactions` (
  `code` VARCHAR(100) NOT NULL,
  `applId` VARCHAR(10) NOT NULL,
  `recordDate` datetime NOT NULL
) ENGINE=InnoDB;

LOAD DATA LOCAL INFILE @infile
INTO TABLE temp_Transactions
FIELDS TERMINATED BY '\0'
LINES TERMINATED BY '\n'
(code, applId, recordDate);

-- Temp table for applications by year for later join.
DROP TABLE IF EXISTS temp_Applications_ByYear;
CREATE TABLE IF NOT EXISTS `temp_Applications_ByYear` (
    `id` INT(11) NOT NULL,
    `applId` varchar(15) NOT NULL,
    UNIQUE KEY `applId_index` (`applId`)
) ENGINE=InnoDB;

INSERT INTO temp_Applications_ByYear (id, applId)
SELECT id, applId FROM Applications WHERE YEAR(filingDate) = @year;

INSERT IGNORE INTO Transactions
   (createdAt, updatedAt, transactionCodeId, applicationId, recordDate)
SELECT NOW(), NOW(), tc.id, tay.id, tt.recordDate
FROM temp_Transactions tt
LEFT JOIN temp_Applications_ByYear tay
ON tay.applId = tt.applId
LEFT JOIN TransactionCodes tc
ON tt.code = tc.code;

DROP TABLE temp_Applications_ByYear;
DROP TABLE temp_Transactions;