-- This template script will read transactions file generated by the go package and load to mysql database

DROP TEMPORARY TABLE IF EXISTS temp_Transactions;
CREATE TEMPORARY TABLE IF NOT EXISTS temp_Transactions LIKE Transactions;

ALTER TABLE temp_Transactions DROP FOREIGN KEY Transactions_ibfk_1;
ALTER TABLE temp_Transactions DROP FOREIGN KEY Transactions_ibfk_2;

DROP INDEX `transactionCodeId` ON temp_Transactions;
DROP INDEX `applicationId` ON temp_Transactions;
DROP INDEX `unique_transaction_constraint` ON temp_Transactions;

ALTER TABLE temp_Transactions MODIFY transactionCodeId VARCHAR(255);
ALTER TABLE temp_Transactions MODIFY applicationId VARCHAR(255);

LOAD DATA LOCAL INFILE @infile
INTO TABLE temp_Transactions
FIELDS TERMINATED BY '^'
LINES TERMINATED BY '$'
(createdAt, updatedAt, transactionCodeId, applicationId, recordDate);

INSERT IGNORE INTO Transactions
   (createdAt, updatedAt, transactionCodeId, applicationId, recordDate)
SELECT tt.createdAt, tt.updatedAt, tc.id AS transactionCodeId, app.id AS applicationId, recordDate
FROM temp_Transactions tt
LEFT JOIN applications app
ON app.applId = tt.applicationId
LEFT JOIN transactionCodes tc
ON tc.code = tt.transactionCodeId;

DROP TEMPORARY TABLE temp_Transactions;